spring.application.name=restapi

#database configurations
spring.datasource.url=jdbc:mysql://localhost:3306/expensetransactions?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=expenseapp
spring.datasource.password=ravi1221
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#JPA properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.servlet.context-path=/api/v1